### PR TITLE
Did a bunch of stuff for #27

### PR DESCRIPTION
**Pull request by atoms118**
I've basically taken care of #27, as well as couple other bugs here and there

I know I can just push to master, but I thought I'd create a PR just in case anybody wanted to check that I didn't screw up something important.

If you don't have the time, that's fine, but it's probably good practice to check PRs in detail for security reasons

### CODE REVIEW

**Comment by atoms118** [comment]
Ah, you're right. I should get this fixed pretty quickly, thanks for pointing that out

**Comment by bvs23bkv33** [comment]
under architectural question i mean following:
if you wanted to speed up comparisions by not calling strcmp where just two ints can be compared than i can point that search in array of strings can be performed with bsearch function, this will provide greater speed up

**Comment by atoms118** [comment]
Yeah, looks like I actually meant to do `memcmp` there, but now that you mention it `strcmp` would be more efficient since the hasher name is actually null terminated, thanks!

In terms of the `bsearch` thing, I'm not exactly sure what you mean. If you could give a code snippet to explain that would be great, but I'm not too concerned with this for now, especially since `pn_data_to_certificate` shouldn't be being called very often in practice

**Comment by atoms118** [comment]
I've commited the changes, approve them when you get the chance (assuming you think they're good)

**Comment by atoms118** [comment]
An example would be `SHA256\0` probably (the `\0` is a null terminator). If this is something you think we should do, go ahead and open an issue for it

**Comment by bvs23bkv33** [comment]
SHA256 is a binary data, not string
strcpy/strncpy can not be used, zero char can be met on any position effectively terminating rest of it
it's length is fixed, no need to store length of every element, they are all the same and constant

**Comment by atoms118** [comment]
Sorry, I didn't mean SHA256 data, I mean the literal string "SHA256". `hasher_name` simply contains a short name to describe the hasher

**Pull request merged**
